apps/chat/src/components/ChatSkeleton.tsx, apps/chat/src/components/PaneBodyBox.tsx, apps/chat/src/components/PaneBox.tsx, apps/chat/src/components/PaneCreateChannel.tsx, apps/chat/src/components/PaneEmpty.tsx, apps/chat/src/components/PaneError.tsx, apps/chat/src/components/PaneHeaderBox.tsx, apps/chat/src/components/PaneHelp.tsx, apps/chat/src/components/PaneLoading.tsx, apps/chat/src/components/PaneLogin.tsx, apps/chat/src/components/PaneSimpleBox.tsx, apps/chat/src/components/PaneSwitch.tsx, apps/chat/src/components/SpaceChatView.tsx, apps/chat/src/components/channel/ChannelPane.tsx, apps/chat/src/components/channel/ChatList.tsx, apps/chat/src/components/pane-profile/PaneProfile.tsx, apps/chat/src/components/settings/PaneSettings.tsx, apps/chat/src/components/sidebar/ChatSidebar.tsx, apps/chat/src/components/sidebar/SidebarHeader.tsx, apps/chat/src/components/space-settings/PaneSpaceSettings.tsx, packages/ui/tailwind.config.js, packages/ui/tailwind.css
The grid layout offers better performance, but is more complex to implement, lacks flexibility, and breaks component encapsulation.
=> Switch grid to flex

apps/server/src/events/tasks.rs, apps/server/src/events/types.rs
=> fix(server): limit the length of cached events

apps/chat/src/components/channel/MessageToolbox.tsx, apps/chat/src/components/channel/MessageToolboxButton.tsx
=> feat(chat): messages archive (fold)

Cargo.lock, apps/server/Cargo.toml, apps/server/src/database.rs, apps/server/src/server.rs
=> feat(server): support connect to database by TLS

apps/chat/src/components/Chat.tsx, apps/chat/src/components/sidebar/BaseUrlSelector.tsx, apps/chat/src/components/sidebar/BaseUrlSelectorItem.tsx, apps/chat/src/hooks/useAutoSelectProxy.tsx, apps/chat/src/hooks/useProxies.tsx, flake.lock, flake.nix
=> Auto Select the Porxy

apps/legacy/src/components/pages/GuestHome.tsx
https://www.cloudflare.com/zh-cn/lp/oss-sponsorship/
=> feat(legacy): add cloudflare link

apps/legacy/src/components/chat/MessageItem.tsx, apps/legacy/src/components/chat/MessageWhisperList.tsx
=> feat(legacy): visually distinguishable unfolding whisper messages

packages/chat/components/compose/Compose.tsx, packages/chat/components/compose/ComposeTextArea.tsx, packages/chat/components/compose/SendButton.tsx, packages/chat/components/compose/useSendPreview.tsx, packages/chat/components/pane-channel/ChannelHeaderCharacterNameEdit.tsx, packages/chat/components/pane-channel/ChannelHeaderMore.tsx, packages/chat/components/pane-channel/ChannelPane.tsx, packages/chat/components/pane-channel/SelfPreview.tsx, packages/chat/components/pane-channel/SelfPreviewNameCell.tsx, packages/chat/components/pane-channel/SelfPreviewSendHelpText.tsx, packages/chat/components/pane-channel/useSend.tsx, packages/chat/hooks/useChannelAtoms.tsx, packages/chat/hooks/useComposeError.tsx, packages/chat/hooks/useEditChannelCharacterName.tsx, packages/chat/hooks/useQueryChannelMembers.tsx, packages/chat/state/compose.reducer.ts, packages/icons/icons/history.svg
=> Character Name

packages/chat/interpreter/parser.ts
=> feat(chat): rh

packages/chat/components/compose/ComposeTextArea.tsx
=> feat(chat): paste media

apps/server/src/server.rs
`head_bucket` needs more permissions.
=> fix(server): S3 check

packages/chat/components/pane-channel/ChatContentDndContext.tsx, packages/chat/components/pane-channel/ChatContentView.tsx, packages/chat/components/pane-channel/ChatContentVirtualList.tsx, packages/chat/components/pane-channel/ChatItemMessage.tsx, packages/chat/components/pane-channel/ChatItemSwitch.tsx, packages/chat/components/pane-channel/DraggingOverlay.tsx
=> fix(chat): game master can't move other people's messages

apps/server/bindings/DiskInfo.ts, apps/server/src/info/handlers.rs, apps/server/src/info/models.rs
=> fix(server): wrong field

package-lock.json, packages/chat/components/entities/Cursor.tsx, packages/chat/components/entities/EntityEmpty.tsx, packages/chat/components/entities/EntityTail.tsx, packages/chat/components/entities/EntityText.tsx, packages/chat/components/entities/TextWithCursor.tsx, packages/chat/components/pane-channel/ChatContentDndContext.tsx, packages/chat/components/pane-channel/ChatContentView.tsx, packages/chat/components/pane-channel/ChatItemMessage.tsx, packages/chat/components/pane-channel/Content.tsx, packages/chat/components/pane-channel/DraggingOverlay.tsx, packages/chat/components/pane-channel/MessageBox.tsx, packages/chat/components/pane-channel/MessageReorderHandle.tsx, packages/chat/components/pane-channel/MessageTime.tsx, packages/chat/components/pane-channel/MessageToolbox.tsx, packages/chat/components/pane-channel/PreviewBox.tsx, packages/chat/components/pane-channel/SelfCursorToolbar.tsx, packages/chat/components/pane-channel/SelfPreviewContent.tsx, packages/chat/components/pane-channel/SelfPreviewNameCell.tsx, packages/chat/hooks/useIsDragging.tsx, packages/chat/package.json, packages/icons/icons/move-vertical.svg
=> Message Related UI

flake.lock, flake.nix
=> fix: no pin flake-parts

.env
https://github.com/vercel/next.js/issues/47121
=> chore(site): disable next telemetry

packages/chat/components/Chat.tsx, packages/chat/hooks/useSetThemeColor.tsx, packages/ui/Button.tsx, packages/ui/tailwind.config.ts
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name/theme-color
=> Support Theme Color

packages/chat/components/pane-channel/ChatItemMessageShowWhisper.tsx
=> feat(chat): auto retrieve whisper messages

apps/server/src/events/preview.rs, packages/chat/components/pane-channel/ChatContentView.tsx, packages/chat/components/pane-channel/ChatItemMessage.tsx, packages/chat/components/sidebar/SidebarChannelItem.tsx, packages/chat/hooks/useReadObserve.tsx, packages/chat/state/unread.atoms.ts
=> Basic Unread Indicator

packages/chat/components/entities/Cursor.tsx, packages/chat/components/entities/EntityHead.tsx, packages/chat/components/pane-channel/ChatContentHeaderLoadMore.tsx, packages/chat/components/pane-channel/ChatContentView.tsx, packages/chat/components/pane-channel/ChatContentVirtualList.tsx, packages/chat/components/pane-channel/ChatItemMessage.tsx, packages/chat/components/pane-channel/ChatItemPreview.tsx, packages/chat/components/pane-channel/ChatItemSwitch.tsx, packages/chat/components/pane-channel/Content.tsx, packages/chat/components/pane-channel/DraggingOverlay.tsx, packages/chat/components/pane-channel/GoBottomButton.tsx, packages/chat/components/pane-channel/OthersPreview.tsx, packages/chat/components/pane-channel/PreviewBox.tsx, packages/chat/components/pane-channel/SelfCursorToolbar.tsx, packages/chat/components/pane-channel/SelfPreview.tsx, packages/chat/components/pane-channel/SelfPreviewContent.tsx, packages/ui/tailwind.config.ts
=> Viewport Position

packages/chat/components/pane-channel/ChatContentView.tsx, packages/chat/components/pane-channel/SelfPreviewContent.tsx
Remove this feature as it doesn't work well on mobile devices
=> feat(chat): remove position scroll by cursor

apps/spa/components/ChatSpace.tsx, apps/spa/components/sidebar/AppOperations.tsx, apps/spa/components/sidebar/Sidebar.tsx, apps/spa/components/sidebar/SidebarChannels.tsx, apps/spa/hooks/useNotificationSwitch.tsx, apps/spa/hooks/useNotify.tsx, apps/spa/state/notification.atoms.ts, packages/ui/tailwind.config.ts
=> Notification

apps/spa/hooks/useNotify.tsx, apps/spa/hooks/useTitle.tsx, apps/spa/state/chat.atoms.ts, apps/spa/state/chat.reducer.tsx
Because there is a risk that the frequency will be limited by the browser.
=> feat(spa): don't use `setInterval`

.env, .github/workflows/check.yaml, apps/server/src/context.rs, packages/utils/src/flags.ts
=> chore: `DEBUG` -> `BOLUO_DEBUG`

apps/spa/public/owlbear-manifest.json
https://docs.owlbear.rodeo/extensions/getting-started
=> feat(spa): try owlbear

apps/server/schema.sql
=> feat(server): remove duplicate index

apps/server/src/cors.rs
=> feat(server): allow CORS connections from IP address

scripts/deploy-preview.sh
Ref: https://github.com/mythal/boluo/pull/447
=> chore: deploy-preview.sh

.sqlx/query-89e9164da69bcf9ffe2a9ed5c105a03fe1e88a5da7852927f91b8049d99e5133.json, apps/legacy/src/api/events.ts, apps/legacy/src/api/messages.ts, apps/legacy/src/reducers/chatState.ts, apps/legacy/src/states/chat-item-set.ts, apps/server/bindings/Message.ts, apps/server/schema.sql, apps/server/sql/messages/export.sql, apps/server/src/messages/models.rs
=> feat: remove `order_date` and `order_offset`

apps/legacy/src/components/chat/compose/useSendPreview.ts, apps/spa/components/compose/useSendPreview.tsx
=> fix: only send previews in the active tab

apps/spa/additional.d.ts, apps/spa/components/Chat.tsx, apps/spa/components/compose/Compose.tsx, apps/spa/components/compose/ComposeTextArea.tsx, apps/spa/components/pane-channel/ChatContentVirtualList.tsx, apps/spa/components/pane-channel/NameEditable.tsx, apps/spa/hooks/useUpdateViewHeight.tsx, apps/spa/hooks/useVirtualKeybroadChange.tsx, apps/spa/tsconfig.json
=> Mobile Keybroad

apps/spa/components/entities/EntityExprBinary.tsx, apps/spa/components/entities/EntityExprCocRoll.tsx, apps/spa/components/entities/EntityExprMax.tsx, apps/spa/components/entities/EntityExprMin.tsx, apps/spa/components/entities/EntityExprRepeat.tsx, apps/spa/components/entities/EntityExprRoll.tsx, apps/spa/components/entities/EntityExprSubExpr.tsx, apps/spa/components/entities/Result.tsx, packages/ui/tailwind.config.ts
=> feat(spa): highlight the final result of a roll

apps/spa/hooks/useChatList.tsx
=> feat(spa): auto hide the preview message

apps/spa/components/pane-channel/useSend.tsx, apps/spa/hooks/useChatList.tsx, apps/spa/state/channel.reducer.ts, apps/spa/state/chat.actions.tsx, packages/api/src/post.ts
=> feat(spa): optimistic send

apps/legacy/src/components/pages/Chat.tsx, apps/site/src/components/global/LocaleProvider.tsx, apps/spa/breakpoint.tsx, apps/spa/components/Chat.tsx, apps/spa/components/ChatSpace.tsx, apps/spa/components/ClientProviders.tsx, apps/spa/components/PaneBox.tsx, apps/spa/components/PaneSwitch.tsx, apps/spa/components/entities/EntityExprBinary.tsx, apps/spa/components/entities/EntityExprSubExpr.tsx, apps/spa/components/pane-channel/ChannelPane.tsx, apps/spa/components/pane-channel/ChatContent.tsx, apps/spa/components/pane-channel/ChatContentDndContext.tsx, apps/spa/components/pane-channel/ChatContentView.tsx, apps/spa/components/pane-channel/ChatItemMessage.tsx, apps/spa/components/pane-channel/ChatItemSwitch.tsx, apps/spa/components/pane-channel/MemberCard.tsx, apps/spa/components/pane-channel/MessageReorderHandle.tsx, apps/spa/components/pane-channel/MessageToolbar.tsx, apps/spa/components/pane-channel/NameBox.tsx, apps/spa/components/pane-channel/SelfPreviewToolbar.tsx, apps/spa/components/pane-space-members/InListButton.tsx, apps/spa/components/sidebar/SidebarChannelList.tsx, apps/spa/components/sidebar/SidebarHeaderButton.tsx, apps/spa/state/view.context.tsx
Ref: https://x.com/acdlite/status/1758229889595977824
=> React 19 Refactoring

.github/workflows/check.yml, .gitignore, flake.nix
Due to https://github.com/nix-community/cache-nix-action/issues/129
=> Revert CI Changes

Cargo.lock, apps/server/Cargo.toml, apps/server/src/server.rs
=> feat(server): mimalloc

apps/legacy/src/components/chat/Connector.tsx, apps/server/src/error.rs, apps/server/src/events/context.rs, apps/server/src/events/handlers.rs, apps/server/src/events/types.rs, apps/spa/hooks/useConnectionEffect.tsx
=> feat(server): check `after`

apps/legacy/src/api/request.ts, apps/legacy/src/api/users.ts, apps/legacy/src/base-url.ts, apps/legacy/src/components/pages/Login.tsx, apps/legacy/src/hooks/useLogout.ts, apps/legacy/src/hooks/useProxyList.ts, apps/legacy/src/utils/token.ts, packages/api-browser/src/index.ts
=> Hotfix 250717
